### ISSUE TITLE
How does it protect from CSRF?

### ISSUE THREAD

**Issue by 40rn05lyv** [sourceclear/headlines#13]
Hi, I don't really understand how your application protects user from CSRF. The only recommended approach is to implement Synchronizer Token Pattern.

**Comment by kickroot** [comment]
After looking at the injectors located at https://github.com/sourceclear/headlines/tree/master/headlines/src/main/java/com/sourceclear/headlines/impl, I've determined there isn't any CSRF protection in Headlines and have removed it from the description.  Thanks for bringing it to my attention!
